// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/common/contact_us/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get contact us",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "get contact us",
                "responses": {}
            }
        },
        "/admin/common/contact_us/{contactId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get contact us",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "get contact us",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contact Id",
                        "name": "contactId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/contact_us/{contactId}/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete contact us",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "delete contact us",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contact Id",
                        "name": "contactId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/contact_us/{contactId}/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update contact us",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "update contact us",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contact Id",
                        "name": "contactId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Contact Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_common_admin.ContactUpdatePayload"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/contact_us_footer/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ContactUsFooter list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "ContactUsFooter list",
                "responses": {}
            }
        },
        "/admin/common/contact_us_footer/{contactId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get contactUs by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "Get contactUs by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contact id",
                        "name": "contactId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/contact_us_footer/{contactId}/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete contact us",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "delete contact us",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contact id",
                        "name": "contactId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/contact_us_footer/{contactId}/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update contact us",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "update contact us",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contact Id",
                        "name": "contactId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "contact us update payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_common_admin.ContactUsFooterUpdatePayload"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/media/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "create media",
                "consumes": [
                    "multipart/data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "file uz",
                        "name": "fileUz",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file ru",
                        "name": "fileRu",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "file en",
                        "name": "fileEn",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/media/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get medias",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "get medias",
                "responses": {}
            }
        },
        "/admin/common/media/{mediaId}/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete media",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "delete media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "media id",
                        "name": "mediaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/media/{mediaId}/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update media",
                "consumes": [
                    "multipart/data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "update media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "media id",
                        "name": "mediaId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file uz",
                        "name": "fileUz",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file ru",
                        "name": "fileRu",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "file en",
                        "name": "fileEn",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/settings/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "create settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "create settings",
                "parameters": [
                    {
                        "description": "Create Settings Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_common_admin.SettingsCreatePayload"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/settings/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "get settings",
                "responses": {}
            }
        },
        "/admin/common/settings/{settingsId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "settings get with setting id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "settings get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "settings Id",
                        "name": "settingsId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/common/settings/{settingsId}/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "settings update by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common-admin"
                ],
                "summary": "settings update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "settings Id",
                        "name": "settingsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "settings update payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_common_admin.SettingsUpdatePayload"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/contact_us/create": {
            "post": {
                "description": "create contact us",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "create contact us",
                "parameters": [
                    {
                        "description": "Contact Us Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_common.ContactCreatePayload"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/contact_us_footer/create": {
            "post": {
                "description": "create contact footer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "create contact footer",
                "parameters": [
                    {
                        "description": "contact us footer create payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_common.ContactUsFooterPayload"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/media/list": {
            "get": {
                "description": "get all media",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "get all media",
                "responses": {}
            }
        },
        "/settings": {
            "get": {
                "description": "get settings list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "get settings",
                "responses": {}
            }
        },
        "/user/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "user create payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_user_admin.UserCreatePayload"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/user/delete/{userId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user Id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/detail/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user Id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "List users",
                "responses": {}
            }
        },
        "/user/login": {
            "post": {
                "description": "Login a user with username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Login a user",
                "parameters": [
                    {
                        "description": "Login User Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_user_admin.UserLoginPayload"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Get user profile",
                "responses": {}
            }
        },
        "/user/update/{userId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-admin"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user Id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update User Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types_user_admin.UserUpdatePayload"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "types_common.ContactCreatePayload": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                }
            }
        },
        "types_common.ContactUsFooterPayload": {
            "type": "object",
            "required": [
                "email",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "types_common_admin.ContactUpdatePayload": {
            "type": "object",
            "properties": {
                "isContacted": {
                    "type": "boolean"
                }
            }
        },
        "types_common_admin.ContactUsFooterUpdatePayload": {
            "type": "object",
            "properties": {
                "isContacted": {
                    "type": "boolean"
                }
            }
        },
        "types_common_admin.SettingsCreatePayload": {
            "type": "object",
            "required": [
                "email",
                "firstPhone",
                "secondPhone"
            ],
            "properties": {
                "addressEn": {
                    "type": "string"
                },
                "addressRu": {
                    "type": "string"
                },
                "addressUz": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "facebookUrl": {
                    "type": "string"
                },
                "firstPhone": {
                    "type": "string"
                },
                "instagramUrl": {
                    "type": "string"
                },
                "secondPhone": {
                    "type": "string"
                },
                "telegramUrl": {
                    "type": "string"
                },
                "workingDays": {
                    "type": "string"
                },
                "youtubeUrl": {
                    "type": "string"
                }
            }
        },
        "types_common_admin.SettingsUpdatePayload": {
            "type": "object",
            "required": [
                "email",
                "firstPhone",
                "secondPhone"
            ],
            "properties": {
                "addressEn": {
                    "type": "string"
                },
                "addressRu": {
                    "type": "string"
                },
                "addressUz": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "facebookUrl": {
                    "type": "string"
                },
                "firstPhone": {
                    "type": "string"
                },
                "instagramUrl": {
                    "type": "string"
                },
                "secondPhone": {
                    "type": "string"
                },
                "telegramUrl": {
                    "type": "string"
                },
                "workingDays": {
                    "type": "string"
                },
                "youtubeUrl": {
                    "type": "string"
                }
            }
        },
        "types_user_admin.UserCreatePayload": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "types_user_admin.UserLoginPayload": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "types_user_admin.UserUpdatePayload": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
