basePath: /
definitions:
  types_common.ContactCreatePayload:
    properties:
      comment:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    required:
    - email
    type: object
  types_common.ContactUsFooterPayload:
    properties:
      email:
        type: string
      fullName:
        type: string
      phone:
        type: string
    required:
    - email
    - phone
    type: object
  types_common_admin.ContactUpdatePayload:
    properties:
      isContacted:
        type: boolean
    type: object
  types_common_admin.ContactUsFooterUpdatePayload:
    properties:
      isContacted:
        type: boolean
    type: object
  types_common_admin.SettingsCreatePayload:
    properties:
      addressEn:
        type: string
      addressRu:
        type: string
      addressUz:
        type: string
      email:
        type: string
      facebookUrl:
        type: string
      firstPhone:
        type: string
      instagramUrl:
        type: string
      secondPhone:
        type: string
      telegramUrl:
        type: string
      workingDays:
        type: string
      youtubeUrl:
        type: string
    required:
    - email
    - firstPhone
    - secondPhone
    type: object
  types_common_admin.SettingsUpdatePayload:
    properties:
      addressEn:
        type: string
      addressRu:
        type: string
      addressUz:
        type: string
      email:
        type: string
      facebookUrl:
        type: string
      firstPhone:
        type: string
      instagramUrl:
        type: string
      secondPhone:
        type: string
      telegramUrl:
        type: string
      workingDays:
        type: string
      youtubeUrl:
        type: string
    required:
    - email
    - firstPhone
    - secondPhone
    type: object
  types_user_admin.UserCreatePayload:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  types_user_admin.UserLoginPayload:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  types_user_admin.UserUpdatePayload:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /admin/common/contact_us/{contactId}:
    get:
      consumes:
      - application/json
      description: get contact us
      parameters:
      - description: contact Id
        in: path
        name: contactId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: get contact us
      tags:
      - common-admin
  /admin/common/contact_us/{contactId}/delete:
    delete:
      consumes:
      - application/json
      description: delete contact us
      parameters:
      - description: contact Id
        in: path
        name: contactId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: delete contact us
      tags:
      - common-admin
  /admin/common/contact_us/{contactId}/update:
    put:
      consumes:
      - application/json
      description: update contact us
      parameters:
      - description: contact Id
        in: path
        name: contactId
        required: true
        type: string
      - description: Update Contact Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_common_admin.ContactUpdatePayload'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: update contact us
      tags:
      - common-admin
  /admin/common/contact_us/list:
    get:
      consumes:
      - application/json
      description: get contact us
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: get contact us
      tags:
      - common-admin
  /admin/common/contact_us_footer/{contactId}:
    get:
      consumes:
      - application/json
      description: Get contactUs by id
      parameters:
      - description: contact id
        in: path
        name: contactId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get contactUs by id
      tags:
      - common-admin
  /admin/common/contact_us_footer/{contactId}/delete:
    delete:
      consumes:
      - application/json
      description: delete contact us
      parameters:
      - description: contact id
        in: path
        name: contactId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: delete contact us
      tags:
      - common-admin
  /admin/common/contact_us_footer/{contactId}/update:
    put:
      consumes:
      - application/json
      description: update contact us
      parameters:
      - description: contact Id
        in: path
        name: contactId
        required: true
        type: string
      - description: contact us update payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_common_admin.ContactUsFooterUpdatePayload'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: update contact us
      tags:
      - common-admin
  /admin/common/contact_us_footer/list:
    get:
      consumes:
      - application/json
      description: ContactUsFooter list
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: ContactUsFooter list
      tags:
      - common-admin
  /admin/common/media/{mediaId}/delete:
    delete:
      consumes:
      - application/json
      description: delete media
      parameters:
      - description: media id
        in: path
        name: mediaId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: delete media
      tags:
      - common-admin
  /admin/common/media/{mediaId}/update:
    put:
      consumes:
      - multipart/data
      description: update media
      parameters:
      - description: media id
        in: path
        name: mediaId
        required: true
        type: string
      - description: file uz
        in: formData
        name: fileUz
        required: true
        type: file
      - description: file ru
        in: formData
        name: fileRu
        type: file
      - description: file en
        in: formData
        name: fileEn
        type: file
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: update media
      tags:
      - common-admin
  /admin/common/media/create:
    post:
      consumes:
      - multipart/data
      description: create media
      parameters:
      - description: file uz
        in: formData
        name: fileUz
        required: true
        type: file
      - description: file ru
        in: formData
        name: fileRu
        type: file
      - description: file en
        in: formData
        name: fileEn
        type: file
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      tags:
      - common-admin
  /admin/common/media/list:
    get:
      consumes:
      - application/json
      description: get medias
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: get medias
      tags:
      - common-admin
  /admin/common/settings/{settingsId}:
    get:
      consumes:
      - application/json
      description: settings get with setting id
      parameters:
      - description: settings Id
        in: path
        name: settingsId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: settings get
      tags:
      - common-admin
  /admin/common/settings/{settingsId}/update:
    put:
      consumes:
      - application/json
      description: settings update by id
      parameters:
      - description: settings Id
        in: path
        name: settingsId
        required: true
        type: string
      - description: settings update payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_common_admin.SettingsUpdatePayload'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: settings update
      tags:
      - common-admin
  /admin/common/settings/create:
    post:
      consumes:
      - application/json
      description: create settings
      parameters:
      - description: Create Settings Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_common_admin.SettingsCreatePayload'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: create settings
      tags:
      - common-admin
  /admin/common/settings/list:
    get:
      consumes:
      - application/json
      description: get settings
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: get settings
      tags:
      - common-admin
  /contact_us/create:
    post:
      consumes:
      - application/json
      description: create contact us
      parameters:
      - description: Contact Us Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_common.ContactCreatePayload'
      produces:
      - application/json
      responses: {}
      summary: create contact us
      tags:
      - common
  /contact_us_footer/create:
    post:
      consumes:
      - application/json
      description: create contact footer
      parameters:
      - description: contact us footer create payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_common.ContactUsFooterPayload'
      produces:
      - application/json
      responses: {}
      summary: create contact footer
      tags:
      - common
  /media/list:
    get:
      consumes:
      - application/json
      description: get all media
      produces:
      - application/json
      responses: {}
      summary: get all media
      tags:
      - common
  /settings:
    get:
      consumes:
      - application/json
      description: get settings list
      produces:
      - application/json
      responses: {}
      summary: get settings
      tags:
      - common
  /user/create:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: user create payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_user_admin.UserCreatePayload'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Create User
      tags:
      - user-admin
  /user/delete/{userId}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: user Id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - user-admin
  /user/detail/{userId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: user Id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get user
      tags:
      - user-admin
  /user/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: List users
      tags:
      - user-admin
  /user/login:
    post:
      consumes:
      - application/json
      description: Login a user with username and password
      parameters:
      - description: Login User Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_user_admin.UserLoginPayload'
      produces:
      - application/json
      responses: {}
      summary: Login a user
      tags:
      - user-admin
  /user/profile:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - user-admin
  /user/update/{userId}:
    put:
      consumes:
      - application/json
      parameters:
      - description: user Id
        in: path
        name: userId
        required: true
        type: string
      - description: Update User Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/types_user_admin.UserUpdatePayload'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update user
      tags:
      - user-admin
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
